// OKF export — a funes star → an OKF Knowledge Bundle. PLAN-0.2.1 Phase 4 (steps 25-27): moved
// here from twinkling's `ts/src/okf-export.ts`, bumped to spec v0.2, and given a transactional
// promotion so a failed export can no longer leave the previous bundle deleted.
//
// EXPORT-ONLY and non-canonical: funes stays the richer canon and this emits the OKF *floor*. The
// mapping carries every funes key the spec has no home for as an extension key, because OKF asks
// consumers to preserve unknown fields — so a well-behaved consumer keeps the funes superset. It
// is ONE-WAY, not a round-trip: [[wikilinks]] become relative markdown links and index.md files
// are REGENERATED as directory listings, so re-importing a bundle would not reconstruct the vault.
//
// Two properties are worth stating before the code, because both were bought with real failures:
//
//   SCOPE. The bundle may contain only what the INDEX sees — de-indexed is de-exported. funes now
//   reads `star.yaml` `index_scope` itself rather than taking a predicate from a caller, and a
//   tombstoned page (superseded/forgotten) is skipped, so a bundle cannot ship a note recall has
//   already retired.
//
//   PROMOTION. The old exporter called `rmSync(outDir)` and then wrote. Every failure after that
//   line — a secret finding, a full disk, a crash — left the user with no bundle at all, and the
//   secret belt's own remedy was to delete the bundle again. The sequence below never removes the
//   live bundle until a complete, scanned replacement is sitting beside it.
import { existsSync, lstatSync, mkdirSync, readdirSync, readFileSync, realpathSync, renameSync, rmSync, statSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { basename, dirname, join, relative, resolve, sep } from "node:path";
import { stringify as stringifyYaml } from "yaml";
import { isTombstoned, type MemoryMeta } from "funes-core";
import { withWriteLock } from "funes-shared";
import { parseFrontmatter } from "./markdown.ts";
import { redact } from "./redact.ts";

/** OKF's reserved filenames — never concept documents; regenerated by the exporter. */
const RESERVED = new Set(["index.md", "log.md"]);
/** Dirs never treated as knowledge (dotdirs handled separately). */
const SKIP_DIRS = new Set(["node_modules", "out_okf"]);

/** The v0.2 keys this mapper OWNS. A key here is consumed from the page's frontmatter and emitted
 *  (or deliberately dropped); everything else rides through verbatim as an extension. */
const OKF_V02_FIELDS = [
  "type", "title", "description", "resource", "tags", "timestamp",
  "sources", "status", "stale_after", "generated",
] as const;
/** Read by the mapper and never copied through: `write_actor` is a STAMPED server fact that funes
 *  keeps index-side, and a bundle that published it would be publishing an authentication detail
 *  no reader asked for. `valid_until` and `status` are consumed conditionally, in the mapper. */
const DROPPED = new Set(["write_actor"]);

export const OKF_VERSION = "0.2";
/** The bundle root's sentinel keys. `okf_star_id` is what makes the target precondition safe: two
 *  stars whose vault basenames collide resolve to the same default out dir, and without an id in
 *  the marker each would happily replace the other's bundle. */
const STAR_ID_KEY = "okf_star_id";

// ── frontmatter rendering ─────────────────────────────────────────────────────────────────────
// funes parses frontmatter (markdown.ts) but never wrote any; the exporter is the first writer, so
// the dump half lands here rather than widening the parser's module.

export type Frontmatter = Record<string, unknown>;

/** Render frontmatter + body. Key order is INSERTION order, which is what makes two exports of an
 *  unchanged vault byte-identical. */
export function dumpFrontmatter(data: Frontmatter, body: string): string {
  if (!data || Object.keys(data).length === 0) return body;
  const fmText = stringifyYaml(data, { lineWidth: 0 }).replace(/\n+$/, "");
  return `---\n${fmText}\n---\n${body}`;
}

// ── the walk ──────────────────────────────────────────────────────────────────────────────────

/** Recursively list content .md files as vault-relative POSIX paths. Skips dotdirs, SKIP_DIRS, the
 *  output dir (`skipAbs`), `.summary.md` derivatives (never indexed — the walkMd view), anything
 *  `exclude` rejects (index_scope-honoring: called with `<relDir>/` before descending and
 *  `<relFile>` per file), and — critically — SYMLINKS: `lstatSync` never follows them, so a vault
 *  symlink (this estate has ~21GB symlinked out) cannot recurse out of the tree, leak external
 *  markdown into the bundle, or loop.
 *
 *  It reads nothing. The tombstone rule needs each page's frontmatter and so does the mapping, so
 *  that read happens ONCE, in buildBundle. */
export function walkPages(
  root: string,
  rel = "",
  skipAbs?: Set<string>,
  exclude?: (rel: string) => boolean,
): string[] {
  const out: string[] = [];
  for (const name of readdirSync(join(root, rel)).sort()) {
    if (name.startsWith(".")) continue;
    const childRel = rel ? `${rel}/${name}` : name;
    const abs = join(root, childRel);
    const st = lstatSync(abs);          // lstat, NOT stat — do not follow symlinks
    if (st.isSymbolicLink()) continue;  // may point outside the vault, or loop
    if (st.isDirectory()) {
      if (SKIP_DIRS.has(name) || skipAbs?.has(abs)) continue;
      if (exclude?.(`${childRel}/`)) continue; // dir prune (trailing-slash form)
      out.push(...walkPages(root, childRel, skipAbs, exclude));
    } else if (name.endsWith(".md") && !name.endsWith(".summary.md")) {
      if (exclude?.(childRel)) continue;
      out.push(childRel);
    }
  }
  return out;
}

// ── target preconditions ──────────────────────────────────────────────────────────────────────

/** RETAINED VERBATIM from twinkling (stack-review CRITICAL, Codex-tightened). The export replaces
 *  its target, so replacement is legal ONLY when the target is (a) absent, (b) an empty directory,
 *  or (c) a previous OKF bundle (root index.md carries `okf_version`). The vault root or any
 *  ancestor of it is refused unconditionally — `--out <vault>` must never take the star. Realpath-
 *  resolved where possible so a symlinked target cannot dodge the containment check. */
export function assertSafeOutDir(outAbs: string, vaultAbs: string): void {
  const real = (p: string): string => { try { return realpathSync(p); } catch { return p; } };
  const o = real(outAbs);
  const v = real(vaultAbs);
  if (o === v || v.startsWith(o + sep)) {
    throw new Error(`okf-export: refusing --out ${outAbs} — it is the vault root or an ancestor of it (the export replaces its target)`);
  }
  if (!existsSync(o)) return;                       // fresh target
  if (!statSync(o).isDirectory()) {
    throw new Error(`okf-export: refusing --out ${outAbs} — exists and is not a directory`);
  }
  if (readdirSync(o).length === 0) return;          // empty dir
  try {
    const marker = readMarker(join(o, "index.md"));
    if (marker.okf_version != null) return;         // a previous bundle
  } catch { /* no/unreadable root index.md ⇒ not a bundle */ }
  throw new Error(`okf-export: refusing --out ${outAbs} — non-empty and not a previous OKF bundle (no okf_version marker); pick an empty or new directory`);
}

function readMarker(indexPath: string): Frontmatter {
  return parseFrontmatter(readFileSync(indexPath, "utf8")).data;
}

/** Step 26's added precondition, on top of assertSafeOutDir: the bundle we are about to replace
 *  must be OURS. An existing bundle stamped with another star's id is refused rather than backed
 *  up and overwritten — two stars whose vault basenames collide share a default out dir, and the
 *  second export would otherwise silently take the first star's bundle. A bundle with NO id (one
 *  this exporter wrote before v0.2) is accepted: refusing it would strand every existing bundle. */
export function assertReplaceableTarget(outAbs: string, starId: string | null): void {
  if (!existsSync(outAbs)) return;
  if (readdirSync(outAbs).length === 0) return;
  let stamped: unknown;
  try { stamped = readMarker(join(outAbs, "index.md"))[STAR_ID_KEY]; } catch { return; }
  if (stamped == null) return;
  if (starId != null && stamped === starId) return;
  throw new Error(
    `okf-export: refusing to replace the bundle at ${outAbs} — it is stamped "${String(stamped)}" and this export is ` +
    `${starId == null ? "from a star that declares no id" : `"${starId}"`}. Two stars must not overwrite each other's bundles; pass --out.`,
  );
}

/** A symlinked out dir is refused outright: every containment check above resolves the link, so a
 *  later attacker-controlled retarget would move the writes somewhere the checks never saw. */
function assertNotSymlink(outAbs: string): void {
  let st;
  try { st = lstatSync(outAbs); } catch { return; } // absent is fine
  if (st.isSymbolicLink()) {
    throw new Error(`okf-export: refusing --out ${outAbs} — it is a symlink; pass the real directory`);
  }
}

// ── link rewriting ────────────────────────────────────────────────────────────────────────────

/** basename-stem → relative path, for bare `[[stem]]` links. Ambiguous stems map to null. */
export function buildStemIndex(relPaths: string[]): Map<string, string | null> {
  const idx = new Map<string, string | null>();
  for (const p of relPaths) {
    const stem = basename(p, ".md");
    idx.set(stem, idx.has(stem) ? null : p); // second sighting ⇒ ambiguous ⇒ null
  }
  return idx;
}

/** Resolve a wikilink target to a bundle-relative path, or null when it does not resolve. */
export function resolveTarget(target: string, pages: Set<string>, stemIndex: Map<string, string | null>): string | null {
  const clean = target.trim();
  // Reject absolute + traversal targets BEFORE the bare-stem fallback: `[[../../secret/beta]]`
  // must NOT silently resolve to an unrelated `beta.md` inside the bundle.
  if (clean.startsWith("/") || clean.split("/").some((seg) => seg === "." || seg === "..")) return null;
  const asPath = clean.endsWith(".md") ? clean : `${clean}.md`;
  return pages.has(asPath) ? asPath : stemIndex.get(basename(clean, ".md")) ?? null;
}

/** Resolve a wikilink to a markdown link RELATIVE to `fromRel`, or null. */
export function resolveLink(
  target: string,
  fromRel: string,
  pages: Set<string>,
  stemIndex: Map<string, string | null>,
): string | null {
  const targetRel = resolveTarget(target, pages, stemIndex);
  if (!targetRel) return null;
  const relPath = relative(dirname(fromRel), targetRel).split(sep).join("/");
  return relPath.startsWith(".") ? relPath : `./${relPath}`; // keep it an explicit relative link
}

/** Percent-encode a POSIX relative link path (segment-wise, so `/` and `.`/`..` survive) + escape a
 *  markdown link label. Defends against spaces / unicode / `]()#` in filenames and aliases. */
const encPath = (p: string): string => p.split("/").map((s) => encodeURIComponent(s).replace(/%2F/gi, "/")).join("/");
const escLabel = (s: string): string => s.replace(/([\\\[\]()])/g, "\\$1");

/** Convert `[[target]]` / `[[target|alias]]` / `[[target#anchor]]` to markdown links. An
 *  unresolvable target is left as-is (OKF tolerates broken cross-links) rather than emitting a
 *  dead link. Body links stay RELATIVE — the absolute form appears only in `sources[].resource`. */
export function convertWikilinks(
  body: string,
  fromRel: string,
  pages: Set<string>,
  stemIndex: Map<string, string | null>,
): string {
  return body.replace(/\[\[([^\]]+)\]\]/g, (whole, inner: string) => {
    const [lhs = "", alias] = inner.split("|");
    const [target = "", anchor] = lhs.split("#");
    const resolved = resolveLink(target, fromRel, pages, stemIndex);
    if (!resolved) return whole;
    const text = escLabel((alias ?? target).trim());
    const href = anchor ? `${encPath(resolved)}#${encodeURIComponent(anchor.trim())}` : encPath(resolved);
    return `[${text}](${href})`;
  });
}

// ── v0.2 value rules (step 27) ────────────────────────────────────────────────────────────────

/** OKF v0.2 §5: "Every timestamp-valued key in OKF is an ISO 8601 datetime with an explicit UTC
 *  offset." A date-only value is valid ISO-8601 and NOT a valid OKF timestamp, so it may not be
 *  emitted as one. This is the whole rule, and it is why so few pages produce a `timestamp`. */
export function isOkfInstant(v: unknown): v is string {
  if (typeof v !== "string") return false;
  if (!/^\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}(:\d{2}(\.\d+)?)?(Z|[+-]\d{2}:?\d{2})$/.test(v.trim())) return false;
  return !Number.isNaN(Date.parse(v.trim()));
}

/** The three status values the spec names. Anything else is a funes legacy value and rides as an
 *  extension rather than being coerced into a vocabulary it does not belong to. */
const OKF_STATUS = new Set(["draft", "stable", "deprecated"]);

/** A URL's stable id: scheme dropped, host + path slugged. Deterministic, so re-exporting an
 *  unchanged vault produces the same bytes. */
export function urlSourceId(url: string): string {
  return url.replace(/^[a-z][a-z0-9+.-]*:\/\//i, "").replace(/[^A-Za-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 120) || "source";
}

const isUrl = (s: string): boolean => /^[a-z][a-z0-9+.-]*:\/\//i.test(s.trim());

export interface SourceMapping {
  sources: Array<{ id: string; resource?: string }>;
  /** Entries that resolved to nothing — kept verbatim under an extension key, and reported. */
  unresolved: string[];
}

/** Map a page's `sources:` — mixed by history, one shape by the end. A valid v0.2 object passes
 *  through; a `[[id]]` or bare id becomes `{id, resource}` pointing at the bundle path (ABSOLUTE,
 *  the one place absolute form is allowed); a URL becomes `{id: <derived>, resource: <url>}`;
 *  anything else is prose we refuse to guess about, so it is preserved and reported. */
export function mapSources(raw: unknown, pages: Set<string>, stemIndex: Map<string, string | null>): SourceMapping {
  const list = Array.isArray(raw) ? raw : raw == null ? [] : [raw];
  const sources: Array<{ id: string; resource?: string }> = [];
  const unresolved: string[] = [];
  for (const entry of list) {
    if (entry && typeof entry === "object" && !Array.isArray(entry)) {
      const o = entry as Record<string, unknown>;
      if (typeof o.id === "string" && o.id.trim()) {
        sources.push(typeof o.resource === "string" ? { id: o.id, resource: o.resource } : { id: o.id });
        continue;
      }
      unresolved.push(JSON.stringify(entry));
      continue;
    }
    if (typeof entry !== "string" || !entry.trim()) { unresolved.push(String(entry)); continue; }
    const s = entry.trim();
    if (isUrl(s)) { sources.push({ id: urlSourceId(s), resource: s }); continue; }
    const bare = s.replace(/^\[\[/, "").replace(/\]\]$/, "").trim();
    const targetRel = resolveTarget(bare, pages, stemIndex);
    if (targetRel) { sources.push({ id: bare, resource: `/${targetRel}` }); continue; }
    unresolved.push(s);
  }
  return { sources, unresolved };
}

export interface ConceptResult {
  text: string;
  /** Non-fatal notes for the operator — an id and what could not be mapped. */
  warnings: string[];
}

/** Map one funes page to an OKF v0.2 concept document. Guarantees a non-empty `type` (the spec's
 *  only hard requirement) and preserves every unmapped funes key as an extension field. */
export function pageToOkfConcept(
  data: Frontmatter,
  body: string,
  fromRel: string,
  pages: Set<string>,
  stemIndex: Map<string, string | null>,
): ConceptResult {
  const okf: Frontmatter = {};
  const warnings: string[] = [];

  okf.type = (typeof data.type === "string" && data.type.trim()) || "note";
  if (data.title != null) okf.title = data.title;
  if (data.description != null) okf.description = data.description;
  if (data.resource != null) okf.resource = data.resource;
  if (data.tags != null) okf.tags = data.tags;

  // timestamp — emitted ONLY when the value already carries an explicit offset (§5). A date-only
  // or naive value is not lost: it stays under the key it rode in on, and `created`/`updated` are
  // never consumed, so the dates remain queryable as extension keys. Spec-clean by §11, which
  // tells consumers not to reject a document for a missing optional field.
  const tsCandidate = data.timestamp ?? data.updated ?? data.created;
  if (isOkfInstant(tsCandidate)) okf.timestamp = tsCandidate;
  else if (data.timestamp != null) okf.funes_timestamp = data.timestamp;

  // sources — the one place an absolute path appears.
  if (data.sources != null) {
    const m = mapSources(data.sources, pages, stemIndex);
    if (m.sources.length) okf.sources = m.sources;
    if (m.unresolved.length) {
      okf.funes_sources_unresolved = m.unresolved;
      warnings.push(`${fromRel}: ${m.unresolved.length} source(s) are neither a resolvable id nor a URL — preserved under funes_sources_unresolved`);
    }
  }

  // status — normalize only the three the spec names; a legacy value rides as an extension rather
  // than being coerced into a vocabulary that does not contain it.
  if (data.status != null) {
    const s = typeof data.status === "string" ? data.status.trim().toLowerCase() : "";
    if (OKF_STATUS.has(s)) okf.status = s;
    else okf.funes_status = data.status;
  }

  // stale_after: a page that already declares one in v0.2 form keeps it; otherwise `valid_until`
  // becomes one, but ONLY when it parses as an absolute instant. A `valid_until` that does not
  // stays `valid_until`, verbatim, through the passthrough below.
  if (isOkfInstant(data.stale_after)) okf.stale_after = data.stale_after;
  else if (isOkfInstant(data.valid_until)) okf.stale_after = data.valid_until;

  // generated: {by, at} — ONLY from an explicit, validated v0.2-form declaration. `source:` is a
  // DECLARED origin, not an actor, and `write_actor` is a server fact funes keeps index-side; if
  // either were accepted here the bundle would attribute authorship to something that never
  // claimed it. Producers may start writing `generated:` and it passes straight through.
  const g = data.generated;
  if (g && typeof g === "object" && !Array.isArray(g)) {
    const o = g as Record<string, unknown>;
    if (typeof o.by === "string" && o.by.trim() && isOkfInstant(o.at)) okf.generated = { by: o.by, at: o.at };
    else {
      okf.funes_generated = g;
      warnings.push(`${fromRel}: \`generated\` is not v0.2-shaped ({by: string, at: <offset datetime>}) — preserved under funes_generated`);
    }
  }

  // Everything else verbatim: OKF consumers MUST keep unknown fields, so this is what makes the
  // bundle carry the funes superset rather than a lossy floor. `valid_until` is skipped only when
  // it became `stale_after`; there is no `verified:` in this mapping at all.
  for (const [k, v] of Object.entries(data)) {
    if ((OKF_V02_FIELDS as readonly string[]).includes(k)) continue;
    if (DROPPED.has(k)) continue;
    if (k === "valid_until" && okf.stale_after != null) continue;
    okf[k] = v;
  }
  return { text: dumpFrontmatter(okf, convertWikilinks(body, fromRel, pages, stemIndex)), warnings };
}

// ── the secret gate (step 26) ─────────────────────────────────────────────────────────────────

export interface ScanResult {
  /** Findings from the pure detector, which always runs. */
  regexFindings: Array<{ file: string; kinds: Record<string, number> }>;
  /** Findings from the gitleaks binary; empty when it did not run. */
  gitleaks: string[];
  /** false ⇒ gitleaks was not runnable. Never a pass on its own — the pure detector is the floor. */
  gitleaksRan: boolean;
}

/** Scan a built bundle. `redact()` runs over EVERY file, always, and a nonzero count fails the
 *  export; gitleaks runs additionally when the binary is on PATH and its findings fail it too.
 *
 *  Why not `gitleaksRedact`: it returns the text UNCHANGED with `scanned: false` when gitleaks is
 *  absent, which is the right fail-open posture for a vault-local distill and exactly the wrong
 *  one here. A bundle exists to be handed to someone else. */
export function scanBundle(dir: string): ScanResult {
  const regexFindings: ScanResult["regexFindings"] = [];
  const walk = (rel: string): void => {
    for (const name of readdirSync(join(dir, rel))) {
      const childRel = rel ? `${rel}/${name}` : name;
      const st = lstatSync(join(dir, childRel));
      if (st.isDirectory()) { walk(childRel); continue; }
      if (!st.isFile()) continue;
      const r = redact(readFileSync(join(dir, childRel), "utf8"));
      if (r.count > 0) regexFindings.push({ file: childRel, kinds: r.kinds });
    }
  };
  walk("");

  // node:child_process, not Bun.spawnSync: the published artifact runs on Node, and the release
  // gate proves it with bun kept off PATH.
  let gitleaksRan = false;
  const gitleaks: string[] = [];
  try {
    const scan = spawnSync("gitleaks", ["dir", dir, "--no-banner", "--redact"], { encoding: "utf8" });
    if (!scan.error && typeof scan.status === "number") {
      gitleaksRan = true;
      if (scan.status !== 0) {
        gitleaks.push(...`${scan.stdout ?? ""}${scan.stderr ?? ""}`.split("\n").filter(Boolean).slice(-12));
      }
    }
  } catch { /* absent or unrunnable — the pure detector already ran and is the floor */ }
  return { regexFindings, gitleaks, gitleaksRan };
}

// ── the export ────────────────────────────────────────────────────────────────────────────────

export interface OkfExportResult {
  concepts: number;
  indexes: number;
  outDir: string;
  warnings: string[];
  /** true ⇒ gitleaks ran in addition to the pure detector. */
  gitleaksRan: boolean;
  /** A backup this run could not remove because a target was already in place — never deleted. */
  strandedBackup?: string;
}

export interface OkfExportOpts {
  /** index_scope-honoring predicate: de-indexed = de-exported. */
  exclude?: (rel: string) => boolean;
  /** The star's id, stamped into the bundle marker and required to replace a stamped bundle. */
  starId?: string | null;
  /** Lock wait before giving up on another exporter (ms). */
  timeoutMs?: number;
}

/** Default bundle home: in-star `out_okf/`, beside the knowledge it distils (ADR-0006). The
 *  eviction to ~/.twinkling was Dropbox-era — no per-folder ignores, so a derived bundle rode every
 *  sync. Syncthing's .stignore ends that; SKIP_DIRS and star.yaml keep the bundle out of the scan
 *  and out of recall. FUNES_OKF_DIR still restores a shared off-vault home, old layout. */
export const okfDefaultOutDir = (vaultRoot: string): string =>
  process.env.FUNES_OKF_DIR
    ? join(process.env.FUNES_OKF_DIR, basename(resolve(vaultRoot)))
    : join(resolve(vaultRoot), "out_okf");

const TMP_RE = /^\.okf-tmp-/;
const BAK_RE = /^\.okf-bak-/;

/** Crash recovery, run under the lock before anything else touches the target. Every combination
 *  the promotion sequence can be interrupted in has a defined outcome:
 *    • a backup with NO target        → the rename that would have restored it never ran: restore it.
 *    • a temp dir                     → the lock is exclusive, so nothing owns it: delete it.
 *    • a backup AND a target          → the target is the newer, complete bundle and WINS; the
 *                                       backup is reported for manual review and never auto-deleted,
 *                                       because "probably stale" is not a reason to delete data. */
function recoverInterrupted(parent: string, name: string): { stranded?: string } {
  const target = join(parent, name);
  let entries: string[];
  try { entries = readdirSync(parent); } catch { return {}; }
  // Prefix-EXACT, not `includes`: sibling bundles live in the same parent, so a target named `a`
  // must not adopt `.okf-bak-abc-…` as its own interrupted backup and restore it over `a`.
  const mine = (prefix: string) => (e: string): boolean => e.startsWith(`${prefix}${name}-`);
  const backups = entries.filter(mine(".okf-bak-")).sort();
  for (const t of entries.filter(mine(".okf-tmp-"))) {
    rmSync(join(parent, t), { recursive: true, force: true });
  }
  if (backups.length === 0) return {};
  if (!existsSync(target)) {
    renameSync(join(parent, backups[backups.length - 1]!), target); // newest wins the restore
    for (const b of backups.slice(0, -1)) rmSync(join(parent, b), { recursive: true, force: true });
    return {};
  }
  return { stranded: join(parent, backups[backups.length - 1]!) };
}

/** Export the star at `vaultRoot` to an OKF bundle at `outDir`, transactionally. */
export async function exportOkf(
  vaultRoot: string,
  outDir = okfDefaultOutDir(vaultRoot),
  opts: OkfExportOpts = {},
): Promise<OkfExportResult> {
  const vaultAbs = resolve(vaultRoot);
  const outAbs = resolve(outDir);
  const parent = dirname(outAbs);
  const name = basename(outAbs);
  const starId = opts.starId ?? null;

  // ONE exclusive lock, held from preflight through cleanup. Keyed on the OUTPUT PATH, so two
  // exports of different stars run concurrently and two exports of the SAME target never do. This
  // reuses funes' own write lock rather than porting a second one: it already records holder pid +
  // token, reclaims a lock whose owner is demonstrably dead (ESRCH only, so an EPERM-on-another-
  // user's-process is never mistaken for death), and refuses to delete a lock reclaimed under it.
  return withWriteLock(outAbs, async () => {
    mkdirSync(parent, { recursive: true });
    const recovered = recoverInterrupted(parent, name);

    assertNotSymlink(outAbs);
    assertSafeOutDir(outAbs, vaultAbs);
    // ADR-0006: an in-vault bundle must be OUTSIDE recall's scope, or the next reindex ingests the
    // bundle's pages as duplicate concepts. Fail closed, exactly like the secret gate. The dir-form
    // probe (`<rel>/`) is the same shape walkMd asks before it descends.
    if (outAbs.startsWith(vaultAbs + sep) && !opts.exclude?.(`${relative(vaultAbs, outAbs)}/`)) {
      throw new Error(
        `okf-export: refusing ${outAbs} — inside the vault and not excluded from index_scope; add ` +
        `"${relative(vaultAbs, outAbs)}/**" to star.yaml memory.index_scope.exclude, or export off-vault (FUNES_OKF_DIR / --out)`,
      );
    }
    assertReplaceableTarget(outAbs, starId);

    const txn = randomBytes(6).toString("hex");
    const tmpAbs = join(parent, `.okf-tmp-${name}-${txn}`);
    rmSync(tmpAbs, { recursive: true, force: true });

    let built: { concepts: number; indexes: number; warnings: string[] };
    try {
      built = buildBundle(vaultAbs, tmpAbs, outAbs, starId, opts.exclude);
    } catch (e) {
      rmSync(tmpAbs, { recursive: true, force: true });
      throw e;
    }

    // Scan the BUILD, before it is anywhere a reader could find it. A failure here leaves the
    // previous bundle exactly as it was, which is the whole reason the sequence is shaped this way.
    const scan = scanBundle(tmpAbs);
    if (scan.regexFindings.length > 0 || scan.gitleaks.length > 0) {
      rmSync(tmpAbs, { recursive: true, force: true });
      const lines = scan.regexFindings.map((f) => `  ${f.file}: ${Object.entries(f.kinds).map(([k, n]) => `${k}×${n}`).join(", ")}`);
      throw new Error(
        `okf-export: ABORTED — secret material in the bundle. Nothing was published and the previous bundle is untouched.\n` +
        (lines.length ? `${lines.join("\n")}\n` : "") +
        (scan.gitleaks.length ? `  gitleaks:\n${scan.gitleaks.map((l) => `    ${l}`).join("\n")}\n` : "") +
        "  Fix the source pages; a bundle exists to be shared, so it cannot ship unscannable.",
      );
    }

    // Promote. Backup first so a crash between the two renames leaves a restorable state, and the
    // backup is deleted only once the target is verifiably in place.
    const bakAbs = join(parent, `.okf-bak-${name}-${Date.now()}-${txn}`);
    const hadTarget = existsSync(outAbs);
    if (hadTarget) renameSync(outAbs, bakAbs);
    try {
      renameSync(tmpAbs, outAbs);
    } catch (e) {
      if (hadTarget) renameSync(bakAbs, outAbs); // put the user's bundle back before reporting
      rmSync(tmpAbs, { recursive: true, force: true });
      throw e;
    }
    if (hadTarget) rmSync(bakAbs, { recursive: true, force: true });

    return {
      ...built,
      outDir: outAbs,
      gitleaksRan: scan.gitleaksRan,
      ...(recovered.stranded ? { strandedBackup: recovered.stranded } : {}),
    };
  }, { timeoutMs: opts.timeoutMs });
}

/** Write the bundle into `buildDir`. `finalAbs` is where it will END UP, and it is excluded from
 *  the walk so a bundle inside the vault can never fold itself in. */
function buildBundle(
  vaultAbs: string,
  buildDir: string,
  finalAbs: string,
  starId: string | null,
  exclude?: (rel: string) => boolean,
): { concepts: number; indexes: number; warnings: string[] } {
  const relPaths = walkPages(vaultAbs, "", new Set([finalAbs, buildDir]), exclude);

  // Read ONCE, then decide. Step 25's tombstone rule needs each page's frontmatter, and so does the
  // mapping — reading in the walk and again here would double the I/O, which is free on a normal
  // filesystem and emphatically not on the Dropbox-backed vaults this estate runs on.
  //
  // ponytail: peak memory is the vault's markdown, which is the same order as the bundle this
  // function is about to write. Stream it in two passes if a star ever outgrows that.
  const sources: Array<{ rel: string; data: Frontmatter; body: string }> = [];
  for (const rel of relPaths) {
    if (RESERVED.has(basename(rel))) continue; // reserved files are REGENERATED, never carried
    const parsed = parseFrontmatter(readFileSync(join(vaultAbs, rel), "utf8"));
    // A tombstoned page (superseded or forgotten) is off the index, so it is off the bundle.
    if (isTombstoned(parsed.data as MemoryMeta)) continue;
    sources.push({ rel, data: parsed.data, body: parsed.body });
  }

  const conceptRels = sources.map((s) => s.rel);
  const pages = new Set(conceptRels);
  const stemIndex = buildStemIndex(conceptRels);

  const dirs = new Set<string>([""]);
  const warnings: string[] = [];
  let concepts = 0;
  for (const { rel, data, body } of sources) {
    const mapped = pageToOkfConcept(data, body, rel, pages, stemIndex);
    warnings.push(...mapped.warnings);
    const dst = join(buildDir, rel);
    mkdirSync(dirname(dst), { recursive: true });
    writeFileSync(dst, mapped.text);
    for (let d = dirname(rel); d !== "." && d !== ""; d = dirname(d)) dirs.add(d);
    concepts++;
  }

  // Reserved files: a plain directory listing per dir. Frontmatter appears ONLY at the bundle root,
  // where it carries the version and the star stamp the replace precondition reads back.
  let indexes = 0;
  for (const d of dirs) {
    const here = conceptRels.filter((p) => dirname(p) === (d || "."));
    const subdirs = [...dirs].filter((x) => x !== d && dirname(x) === (d || "."));
    const body = [
      `# ${escLabel(d ? basename(d) : basename(vaultAbs))}`,
      "",
      ...subdirs.sort().map((s) => `- [${escLabel(basename(s))}/](${encPath(basename(s))}/index.md)`),
      ...here.sort().map((p) => `- [${escLabel(basename(p, ".md"))}](${encPath(basename(p))})`),
      "",
    ].join("\n");
    const text = d === ""
      ? dumpFrontmatter({ okf_version: OKF_VERSION, ...(starId ? { [STAR_ID_KEY]: starId } : {}) }, body)
      : body;
    const dst = join(buildDir, d, "index.md");
    mkdirSync(dirname(dst), { recursive: true });
    writeFileSync(dst, text);
    indexes++;
  }
  return { concepts, indexes, warnings };
}
